modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="\u52A8\u529B\u6838\u5FC3"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
